// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69pieAr4IE4rha_nozaOlQuRtMZ_7nGI',
    appId: '1:248566776695:web:97e3808e8f96a1bafe5772',
    messagingSenderId: '248566776695',
    projectId: 'phone-firebase-eb7b1',
    authDomain: 'phone-firebase-eb7b1.firebaseapp.com',
    storageBucket: 'phone-firebase-eb7b1.appspot.com',
    measurementId: 'G-1KETY05YS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7z4a0d8Jl9i9-IhHVyjecr4oCGmu2rhU',
    appId: '1:248566776695:android:bdbb6695a33180d2fe5772',
    messagingSenderId: '248566776695',
    projectId: 'phone-firebase-eb7b1',
    storageBucket: 'phone-firebase-eb7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsg6Dnio5Q7xZJP8609hBwA6whrUA78ew',
    appId: '1:248566776695:ios:08360e10e8bef475fe5772',
    messagingSenderId: '248566776695',
    projectId: 'phone-firebase-eb7b1',
    storageBucket: 'phone-firebase-eb7b1.appspot.com',
    iosBundleId: 'com.example.rajApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsg6Dnio5Q7xZJP8609hBwA6whrUA78ew',
    appId: '1:248566776695:ios:08360e10e8bef475fe5772',
    messagingSenderId: '248566776695',
    projectId: 'phone-firebase-eb7b1',
    storageBucket: 'phone-firebase-eb7b1.appspot.com',
    iosBundleId: 'com.example.rajApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA69pieAr4IE4rha_nozaOlQuRtMZ_7nGI',
    appId: '1:248566776695:web:66251ca7ab50fb1bfe5772',
    messagingSenderId: '248566776695',
    projectId: 'phone-firebase-eb7b1',
    authDomain: 'phone-firebase-eb7b1.firebaseapp.com',
    storageBucket: 'phone-firebase-eb7b1.appspot.com',
    measurementId: 'G-9WZW4NSSB3',
  );
}
